String amortedamorte='''A MORTE DA MORTE NA MORTE DE CRISTO:
UM TRATADO DA REDENÇÃO E RECONCILIAÇÃO QUE ESTÁ NO SANGUE DE CRISTO;
COM
O MÉRITO DO MESMO E A SATISFAÇÃO ADQUIRIDA:
EM QUE
O FIM ADEQUADO DA MORTE DE CRISTO É AFIRMADO; OS EFEITOS IMEDIATOS E OS FRUTOS ATRIBUÍDOS, COM SUA EXTENSÃO EM RELAÇÃO AO SEU OBJETO;
E A
TODA A CONTROVÉRSIA SOBRE A REDENÇÃO UNIVERSAL TOTALMENTE DISCUTIDA.
EM QUATRO PARTES...''';