String adivinelight1='''CRISTO diz estas palavras a Pedro na ocasião em que ele professou sua fé nele como Filho de Deus. Nosso Senhor estava perguntando aos seus discípulos quem os homens diziam que ele era; não que ele precisasse ser informado, mas apenas para introduzir e dar ocasião ao que se segue. Eles respondem que alguns disseram que ele era João Batista, e alguns Elias, e outros Jeremias, ou um dos Profetas. Quando eles prestaram contas de quem os outros disseram que ele era, Cristo lhes perguntou quem eles disseram que ele era? Simão Pedro, que achamos sempre zeloso e atrevido, foi o primeiro a responder: respondeu prontamente à pergunta: Tu és Cristo, o Filho do Deus vivo.''';
String adivinelightverse='Mateus 16:17 - E Jesus, respondendo, disse-lhe: Bem-aventurado és tu, Simão Barjonas, porque não foi carne e sangue que to revelou, mas meu Pai que está nos céus.';
String adivinelight2='''A Benção de Pedro''';
String adivinelight3='''Nesta ocasião, Cristo diz para ele e a respeito dele no texto: no qual podemos observar,''';
String adivinelight4='''Que Ele sabia que Jesus era o Cristo''';
String adivinelight5='''1. Que Pedro é declarado bendito por esse motivo. Bem-aventurado és tu – “Tu és um homem feliz, pois não és ignorante quanto a isto, que eu sou Cristo, o Filho do Deus vivo. Tu és bem aventurado por esta distinção. Outros estão cegos, e tem uma apreenção errônea e obscura daquilo que agora declaraste, alguns pensam que eu sou Elias, e alguns que eu sou Jeremias, e alguns uma coisa, e alguns outra; mas nenhum deles está pensando corretamente, todos eles estão enganados. Feliz és tu, que és tão distinto dos demais em saber a verdade sobre este assunto."''';

String adivinelight6='''Que Deus havia revelado isso essa verdade a ele''';
String adivinelight7='''2. A evidência disso foi declarada a respeito dessa distinta felicidade; a saber, que Deus, e somente ele, havia revelado isso a ele. Esta é uma evidência de que ele foi abençoado.''';
String adivinelight8='''Primeiro, pois mostra quão peculiarmente ele foi favorecido por Deus acima dos outros; ex: "Quão altamente favorecido és tu, que outros que são homens sábios e grandes, os escribas, fariseus e governantes, e a nação em geral, são deixados nas trevas, para seguirem suas próprias apreensões equivocadas; e que você foi preterido, por assim dizer, como escolhido por nome. Que meu Pai Celestial deveria assim colocar seu amor em você, Simão Bar-jona. Isso demonstra que você é abençoado, que você deve assim ser o objeto do amor distintivo de Deus.''';
String adivinelight9='''Em segundo lugar, também evidencia a sua bem-aventurança, pois sugere que este conhecimento está acima de qualquer coisa que a carne e o sangue possam revelar. "Este é o conhecimento que somente meu Pai que está nos céus pode dar: é muito elevado e excelente para ser comunicado por meios como outros conhecimentos. Tu és abençoado por saberes aquilo que somente Deus pode te ensinar."''';

String adivinelight10='''Deus o Autor de Todo Conhecimento''';
String adivinelight11='''A origem deste conhecimento é aqui declarada, tanto negativa quanto positivamente. Positivamente, já que Deus é aqui declarado o autor disso. Negativamente, como é declarado, que a carne e o sangue não o revelaram.''';
String adivinelight12='''Todo Conhecimento Moral e Habilidade Pessoal vem de Deus''';
String adivinelight13='''Deus é o autor de todo conhecimento e compreensão. Ele é o autor do conhecimento obtido pelo aprendizado humano: Ele é o autor de toda prudência moral e do conhecimento e habilidade que os homens possuem em seus afazeres secular. Assim, é dito de todos em Israel que eram sábios de coração e hábeis em bordados, que Deus os encheu com o espírito de sabedoria, Êxodo 28:3.''';
String adivinelight14='''Há o Conhecimento em que Carne e Sangue podem Revelar ou Ensinar''';
String adivinelight15='''Deus é o autor de tal conhecimento; Mas, no entanto, a carne e sangue conseguem o revelar, ensinar. Homens mortais são capazes de transmitir o conhecimento das artes e ciências humanas e habilidade em assuntos temporais. Deus é o autor de tal conhecimento por esses meios: carne e sangue são empregados como meio ou segunda causa; Ele o transmite pelo poder e influência dos meios naturais.''';
String adivinelight16='''Deus é e somente Ele é o Autor do Conhecimento Espiritual''';
String adivinelight17='''Mas esse conhecimento espiritual, mencionado no texto, cujo autor é Deus, e mais ninguém: Ele o revela, e a carne e o sangue não o revelam. Ele transmite esse conhecimento imediatamente, sem fazer uso de quaisquer causas naturais intermediárias, como faz com outros conhecimentos.''';


